/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	appv1 "github.com/alauda/helm-crds/pkg/apis/app/v1"
	"github.com/alauda/helm-crds/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type AppV1Interface interface {
	RESTClient() rest.Interface
	ChartsGetter
	ChartReposGetter
	HelmRequestsGetter
	ReleasesGetter
}

// AppV1Client is used to interact with features provided by the app.alauda.io group.
type AppV1Client struct {
	restClient rest.Interface
}

func (c *AppV1Client) Charts(namespace string) ChartInterface {
	return newCharts(c, namespace)
}

func (c *AppV1Client) ChartRepos(namespace string) ChartRepoInterface {
	return newChartRepos(c, namespace)
}

func (c *AppV1Client) HelmRequests(namespace string) HelmRequestInterface {
	return newHelmRequests(c, namespace)
}

func (c *AppV1Client) Releases(namespace string) ReleaseInterface {
	return newReleases(c, namespace)
}

// NewForConfig creates a new AppV1Client for the given config.
func NewForConfig(c *rest.Config) (*AppV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &AppV1Client{client}, nil
}

// NewForConfigOrDie creates a new AppV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *AppV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new AppV1Client for the given RESTClient.
func New(c rest.Interface) *AppV1Client {
	return &AppV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := appv1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *AppV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
